# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:03
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ в административную часть'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин пользователя'),
        ),
        migrations.AlterField(
            model_name='userexaminationanswerlog',
            name='answer_data',
            field=core.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userexaminationquestionlog',
            name='question_data',
            field=core.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userexaminationquestionlog',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
