# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userexamination_must_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='minutes_to_pass',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Сколько минут дано на тест'),
        ),
    ]
