# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examination_minutes_to_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='department',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='user',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='schedulers', to='core.Department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='schedulers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
