# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160326_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexaminationanswerlog',
            options={'verbose_name': 'Лог ответов на вопросы', 'verbose_name_plural': 'Лог ответов на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='userexaminationquestionlog',
            options={'verbose_name': 'Лог ответов', 'verbose_name_plural': 'Лог ответов'},
        ),
        migrations.AddField(
            model_name='userexamination',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexamination',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_examinaions', to='core.Scheduler'),
        ),
    ]
