# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 12:12
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160326_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexaminationquestionlog',
            options={'ordering': ['-skipped_at', 'position'], 'verbose_name': 'Лог ответов', 'verbose_name_plural': 'Лог ответов'},
        ),
        migrations.AddField(
            model_name='userexaminationquestionlog',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexaminationquestionlog',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexaminationquestionlog',
            name='question_answers_data',
            field=core.fields.JSONField(default='[]'),
        ),
        migrations.AddField(
            model_name='userexaminationquestionlog',
            name='skipped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='unit',
            field=models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц')], default='week', help_text='Например: 1 раз в 2 месяца, 3 раза в 1 неделю', max_length=255, verbose_name='Единица измерения периода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userexamination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userexaminationquestionlog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='core.Question'),
        ),
        migrations.AlterField(
            model_name='userexaminationquestionlog',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userexaminationquestionlog',
            name='user_examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.UserExamination'),
        ),
    ]
