# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160402_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexaminationquestionlog',
            options={'ordering': ['skipped_at', 'position'], 'verbose_name': 'Лог ответов', 'verbose_name_plural': 'Лог ответов'},
        ),
        migrations.AlterField(
            model_name='userexaminationanswerlog',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Answer'),
        ),
    ]
