# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:04
from __future__ import unicode_literals

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.UserExcludeDeletedManager()),
                ('default_objects', core.managers.UserDefaultManager()),
            ],
        ),
        migrations.AddField(
            model_name='examination',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
