# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_department_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamination',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
