- name: Run 'apt-get update'
  apt: update_cache=yes

- name: Install needed packages
  apt: pkg={{ item }} state=latest
  with_items: [
    ntp, build-essential, supervisor, git,
    python-dev, python-setuptools, ipython
  ]

